ports = [ 81, 82, 83]

pipeline {
    agent any  // This will run on any available node

    parameters {
        string(name: 'serverIP', defaultValue: 'None', description: 'Enter target Host IP ')
        string(name: 'targetHost', defaultValue: 'None', description: 'Enter target host for deployment ')
        string(name: 'dockerUser', defaultValue: 'None', description: 'Enter Docker user name ')   
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    }

    stages {
        stage('SCM checkout') {
            steps {
                git url: "https://github.com/satishlesnar/appjenkins.git", branch: "main"
            }
        }

        stage('Build deployment image') {
            steps {
                sh "sudo docker build /home/ubuntu/jenkins/workspace/${JOB_NAME} -t ${dockerUser}/devopsdemo --no-cache"
            }
        }

        stage('Push Image') {
            steps {
                sh "echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login --username ${dockerUser} --password-stdin"
                sh "sudo docker push ${dockerUser}/devo
